// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFile(arg1:string):Promise<{[key: string]: any}>;

export function ClearCompressed():Promise<void>;

export function GetConfig():Promise<{[key: string]: any}>;

export function OpenFileDialog():Promise<{[key: string]: any}>;

export function SetConfig(arg1:{[key: string]: any}):Promise<{[key: string]: any}>;
