// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFile(arg1) {
  return window['go']['main']['App']['AddFile'](arg1);
}

export function ClearCompressed() {
  return window['go']['main']['App']['ClearCompressed']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function SetConfig(arg1) {
  return window['go']['main']['App']['SetConfig'](arg1);
}
